const Map<num, String> affirmations ={
  1:"Write it on your heart that every day is the best day in the year.",
  2:"My dear friend, clear your mind of can’t.",
  3:"You’re off to great places, today is your day. Your mountain is waiting, so get on your way.",
  4:"Winning doesn’t always mean being first. Winning means you’re doing better than you’ve done before.",
  5:"It always seems impossible until it is done.",
  6:"All you need is the plan, the road map, and the courage to press on to your destination.",
  7:"A friend may be waiting behind a stranger’s face.",
  8:"Joy is not in things; it is in us.",
  9:"Extraordinary things are always hiding in places people never think to look.",
  10:"The struggle you’re in today is developing the strength you need tomorrow.",
  11:"Stay positive. Better days are on their way.",
  12:"Setting goals is the first step in turning the invisible into the visible.",
  13:"The more you praise and celebrate your life, the more there is in life to celebrate.",
  14:"Whatever is worrying you right now—forget about it. Take a deep breath, stay positive and know things will get better.",
  15:"Nobody can go back and start a new beginning, but anyone can start today and make a new ending.",
  16:"Think big thoughts but relish small pleasures.",
  17:"Today is a good day to try.",
  18:"We may not have hit the peak yet, but we are on the journey up.",
  19:"The things you’re waiting and hoping for tend to arrive at the most unexpected moments.",
  20:"Keep looking up… that’s the secret of life. ",
  21:"Just for the record darling, not all positive change feels positive in the beginning.",
  22:"Every day may not be good... but there’s something good in every day.",
  23:"The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.",
  24:"You are enough just as you are.",
  25:"The first step is you have to say that you can.",
  26:"Keep a smile on your face. Keep a spring in your step.",
  27:"Jump in with both feet and be brave.",
  28:"Life has no limitations, except the ones you make.",
  29:"What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.",
  30:"You are never too old to set another goal or dream a new dream.",
  31:"There is nothing in a caterpillar that tells you it’s going to be a butterfly.",
}; 
